baseurl: ""
url: "https://daszeal.github.io"
title: "Daszeal"
permalink: /:year/:month/:day/:title/

collections:
  posts:
    output: true
    
  pics:
    output: true
    permalink: /pics/:name/

  projects:
    output: true
    permalink: /projects/:name/

plugins:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap
